In [2]:
import pandas as pd
import plotly.express as px

keywords = pd.read_csv("thematics_keywords_new.csv")
keywords

,Channel Title,Country,Week,Category,High Risk Of False Positive,Is Solution,Is Consequence,Is Cause,Is General Concepts,Is Statement,...,Agriculture,Transport,Batiments,Energie,Industrie,Eau,Ecosysteme,Economie Ressources,Count,Sum Duration Minutes
0,RADIO 1,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,80,2 030
1,RADIO 1,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,60,2 030
2,Canvas,belgium,"2 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,48,375
3,Canvas,belgium,"9 February, 2026",Transversal,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,48,375
4,RADIO 1,belgium,"16 March, 2026",General,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,40,2 030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7094,STU BRU,belgium,"11 May, 2026",Transversal,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,1,1 470
7095,STU BRU,belgium,"11 May, 2026",Transversal,True,False,True,False,False,False,...,False,False,False,False,False,False,True,False,1,1 470
7096,STU BRU,belgium,"11 May, 2026",Transversal,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,1,1 470
7097,STU BRU,belgium,"11 May, 2026",Transversal,True,True,False,False,False,False,...,False,True,False,True,False,False,False,False,1,1 470
7098,STU BRU,belgium,"11 May, 2026",Transversal,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,1,1 470

In [3]:
# Renaming the column 0 to "Count"
counts_keywords = keywords.groupby("Keyword").size().reset_index(name="Count")
counts_keywords

              Keyword  Count
0           40 graden      1
1               aarde     62
2             aardgas     18
3            aardolie      5
4    aardverschuiving     24
..                ...    ...
467              zuur      1
468   zware industrie      2
469     zware metalen      4
470   zware stookolie      3
471           zwembad      4

[472 rows x 2 columns]

In [4]:
# Sorting counts_keywords by count (in descending order)
counts_keywords = counts_keywords.sort_values(by="Count", ascending=False)
# Selecting the top 60 most occuring keywords as in this case all words can be read on the x-axis
top_counts = counts_keywords.head(60)

# Creating a bar chart using plotly express
fig = px.bar(top_counts, x="Keyword", y="Count", title="Keyword Frequency")
fig.update_xaxes(tickangle=90)

fig.show()
fig.write_html("charts/Keyword_count.html", full_html=True, include_plotlyjs='cdn')